version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
      args:
        - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    container_name: gym_frontend_prod
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    networks:
      - gym-dorian_default
    restart: always

networks:
  gym-dorian_default:
    external: true
